services:
  # Backend Service
  - type: web
    name: agrosky-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python migrate_db.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: ENVIRONMENT
        value: production
      - key: SENTINEL_CLIENT_ID
        sync: false
      - key: SENTINEL_CLIENT_SECRET
        sync: false
      - key: SENTINEL_INSTANCE_ID
        sync: false

  # Frontend Service
  - type: web
    name: agrosky-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://agrosky-backend.onrender.com
